kind: pipeline
name: default

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: test
  image: golang:1.15
  environment:
    GOPATH: /drone
    GO111MODULE: on
  commands:
    - make deps
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/go/bin v1.35.2
    - make lint
    - make test

# Edge deployment (push a docker image with the edge tag)

- name: docker-cgo-edge
  image: plugins/docker
  settings:
    repo: jeffail/benthos
    dockerfile: resources/docker/Dockerfile.cgo
    tags: edge-cgo
    username: jeffail
    password:
      from_secret: docker_password
  when:
    event: [ push ]
    ref:
      exclude:
      - refs/tags/*-rc*

- name: docker-edge
  image: plugins/docker
  settings:
    repo: jeffail/benthos
    dockerfile: resources/docker/Dockerfile
    tags: edge
    username: jeffail
    password:
      from_secret: docker_password
  when:
    event: [ push ]
    ref:
      exclude:
      - refs/tags/*-rc*

# Tagged deployment (push a docker images and upload binaries to GH releases)

- name: release
  image: golang:1.15
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
    - ./resources/scripts/release_notes.sh > ./release_notes.md
    - curl -sL https://git.io/goreleaser | bash -s -- --release-notes=./release_notes.md
  when:
    event: tag

- name: docker-cgo-tags
  image: golang
  commands:
    - make docker-cgo-tags
  when:
    event: tag
    ref:
      exclude:
      - refs/tags/*-rc*

- name: docker-cgo
  image: plugins/docker
  settings:
    repo: jeffail/benthos
    dockerfile: resources/docker/Dockerfile.cgo
    username: jeffail
    password:
      from_secret: docker_password
  when:
    event: tag
    ref:
      exclude:
      - refs/tags/*-rc*

- name: docker-tags
  image: golang
  commands:
    - make docker-tags
  when:
    event: tag
    ref:
      exclude:
      - refs/tags/*-rc*

- name: docker
  image: plugins/docker
  settings:
    repo: jeffail/benthos
    dockerfile: resources/docker/Dockerfile
    username: jeffail
    password:
      from_secret: docker_password
  when:
    event: tag
    ref:
      exclude:
      - refs/tags/*-rc*

- name: docker-rc-tags
  image: golang
  commands:
    - make docker-rc-tags
  when:
    event: tag
    ref:
    - refs/tags/*-rc*

- name: docker-rc
  image: plugins/docker
  settings:
    repo: jeffail/benthos
    dockerfile: resources/docker/Dockerfile
    username: jeffail
    password:
      from_secret: docker_password
  when:
    event: tag
    ref:
    - refs/tags/*-rc*
